// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence.Database;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(DatabaseService))]
    [Migration("20220706181008_v1")]
    partial class v1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0-preview.5.22302.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Domain.Customers.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Martin Fowler"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Uncle Bob"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Kent Beck"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Brenda Delacruz"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Harvir Estes"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Maurice Boyd"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Claire Lacey"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Mahamed Vincent"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Clayton Whitfield"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Cali Spencer"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Evie-Mai Fountain"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Nia Hook"
                        });
                });

            modelBuilder.Entity("Domain.Employees.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Eric Evans"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Greg Young"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Udi Dahan"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Rhia Hatfield"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Tasnim Stewart"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Neve Kidd"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Ezekiel Zamora"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Donnie Everett"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Renae Mcclure"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Lucian Donald"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Mea Craft"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Neo Black"
                        });
                });

            modelBuilder.Entity("Domain.Products.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasPrecision(6, 3)
                        .HasColumnType("decimal(6,3)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Spaghetti",
                            Price = 5m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Lasagna",
                            Price = 10m
                        },
                        new
                        {
                            Id = 3,
                            Name = "Ravioli",
                            Price = 15m
                        },
                        new
                        {
                            Id = 4,
                            Name = "Salad",
                            Price = 5m
                        },
                        new
                        {
                            Id = 5,
                            Name = "Sandwich",
                            Price = 3m
                        },
                        new
                        {
                            Id = 6,
                            Name = "Tuna Steak",
                            Price = 9m
                        },
                        new
                        {
                            Id = 7,
                            Name = "Shrimp",
                            Price = 12m
                        },
                        new
                        {
                            Id = 8,
                            Name = "Rice",
                            Price = 7m
                        },
                        new
                        {
                            Id = 9,
                            Name = "Pizza",
                            Price = 12m
                        },
                        new
                        {
                            Id = 10,
                            Name = "Hamburger",
                            Price = 8m
                        },
                        new
                        {
                            Id = 11,
                            Name = "Bean sauce",
                            Price = 3m
                        },
                        new
                        {
                            Id = 12,
                            Name = "Brown sugar",
                            Price = 6m
                        },
                        new
                        {
                            Id = 13,
                            Name = "Adobo",
                            Price = 1m
                        },
                        new
                        {
                            Id = 14,
                            Name = "Hoisin sauce",
                            Price = 9m
                        },
                        new
                        {
                            Id = 15,
                            Name = "Sesame seeds",
                            Price = 12m
                        },
                        new
                        {
                            Id = 16,
                            Name = "Cottage cheese",
                            Price = 14m
                        },
                        new
                        {
                            Id = 17,
                            Name = "Chai",
                            Price = 19m
                        },
                        new
                        {
                            Id = 18,
                            Name = "Plantains",
                            Price = 5m
                        },
                        new
                        {
                            Id = 19,
                            Name = "Pasta",
                            Price = 3m
                        },
                        new
                        {
                            Id = 20,
                            Name = "Coconut milk",
                            Price = 12m
                        },
                        new
                        {
                            Id = 21,
                            Name = "Cilantro",
                            Price = 5m
                        },
                        new
                        {
                            Id = 22,
                            Name = "Rabbits",
                            Price = 1m
                        },
                        new
                        {
                            Id = 23,
                            Name = "Plums",
                            Price = 9m
                        },
                        new
                        {
                            Id = 24,
                            Name = "Rice vinegar",
                            Price = 12m
                        },
                        new
                        {
                            Id = 25,
                            Name = "Peanuts",
                            Price = 6m
                        },
                        new
                        {
                            Id = 26,
                            Name = "Jack cheese",
                            Price = 6m
                        },
                        new
                        {
                            Id = 27,
                            Name = "Turkeys",
                            Price = 21m
                        },
                        new
                        {
                            Id = 28,
                            Name = "Broth",
                            Price = 22m
                        },
                        new
                        {
                            Id = 29,
                            Name = "Couscous",
                            Price = 15m
                        },
                        new
                        {
                            Id = 30,
                            Name = "Coconut oil",
                            Price = 18m
                        });
                });

            modelBuilder.Entity("Domain.Sales.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("TotalItems")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Sales");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2022, 7, 3, 0, 0, 0, 0, DateTimeKind.Local),
                            CustomerId = 1,
                            EmployeeId = 1,
                            TotalItems = 0,
                            TotalPrice = 0m
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2022, 7, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            CustomerId = 2,
                            EmployeeId = 2,
                            TotalItems = 0,
                            TotalPrice = 0m
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2022, 7, 5, 0, 0, 0, 0, DateTimeKind.Local),
                            CustomerId = 3,
                            EmployeeId = 3,
                            TotalItems = 0,
                            TotalPrice = 0m
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2022, 7, 5, 0, 0, 0, 0, DateTimeKind.Local),
                            CustomerId = 3,
                            EmployeeId = 3,
                            TotalItems = 0,
                            TotalPrice = 0m
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2022, 7, 5, 0, 0, 0, 0, DateTimeKind.Local),
                            CustomerId = 1,
                            EmployeeId = 2,
                            TotalItems = 0,
                            TotalPrice = 0m
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2022, 7, 5, 0, 0, 0, 0, DateTimeKind.Local),
                            CustomerId = 2,
                            EmployeeId = 3,
                            TotalItems = 0,
                            TotalPrice = 0m
                        });
                });

            modelBuilder.Entity("Domain.SalesProducts.SaleProduct", b =>
                {
                    b.Property<int>("SaleId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("SaleId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("SaleProduct");

                    b.HasData(
                        new
                        {
                            SaleId = 1,
                            ProductId = 1,
                            Id = 1,
                            Quantity = 2
                        },
                        new
                        {
                            SaleId = 1,
                            ProductId = 2,
                            Id = 2,
                            Quantity = 1
                        },
                        new
                        {
                            SaleId = 1,
                            ProductId = 3,
                            Id = 3,
                            Quantity = 1
                        },
                        new
                        {
                            SaleId = 1,
                            ProductId = 4,
                            Id = 4,
                            Quantity = 2
                        },
                        new
                        {
                            SaleId = 1,
                            ProductId = 5,
                            Id = 5,
                            Quantity = 1
                        },
                        new
                        {
                            SaleId = 2,
                            ProductId = 6,
                            Id = 6,
                            Quantity = 1
                        },
                        new
                        {
                            SaleId = 2,
                            ProductId = 7,
                            Id = 7,
                            Quantity = 2
                        },
                        new
                        {
                            SaleId = 3,
                            ProductId = 8,
                            Id = 8,
                            Quantity = 2
                        },
                        new
                        {
                            SaleId = 3,
                            ProductId = 9,
                            Id = 9,
                            Quantity = 3
                        },
                        new
                        {
                            SaleId = 4,
                            ProductId = 10,
                            Id = 10,
                            Quantity = 5
                        },
                        new
                        {
                            SaleId = 5,
                            ProductId = 1,
                            Id = 11,
                            Quantity = 7
                        },
                        new
                        {
                            SaleId = 6,
                            ProductId = 1,
                            Id = 12,
                            Quantity = 3
                        },
                        new
                        {
                            SaleId = 6,
                            ProductId = 2,
                            Id = 13,
                            Quantity = 7
                        },
                        new
                        {
                            SaleId = 6,
                            ProductId = 3,
                            Id = 14,
                            Quantity = 5
                        },
                        new
                        {
                            SaleId = 6,
                            ProductId = 4,
                            Id = 15,
                            Quantity = 4
                        },
                        new
                        {
                            SaleId = 6,
                            ProductId = 5,
                            Id = 16,
                            Quantity = 1
                        });
                });

            modelBuilder.Entity("Domain.Sales.Sale", b =>
                {
                    b.HasOne("Domain.Customers.Customer", "Customer")
                        .WithMany("Sales")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Employees.Employee", "Employee")
                        .WithMany("Sales")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Domain.SalesProducts.SaleProduct", b =>
                {
                    b.HasOne("Domain.Products.Product", "Product")
                        .WithMany("SaleProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Sales.Sale", "Sale")
                        .WithMany("SaleProducts")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("Domain.Customers.Customer", b =>
                {
                    b.Navigation("Sales");
                });

            modelBuilder.Entity("Domain.Employees.Employee", b =>
                {
                    b.Navigation("Sales");
                });

            modelBuilder.Entity("Domain.Products.Product", b =>
                {
                    b.Navigation("SaleProducts");
                });

            modelBuilder.Entity("Domain.Sales.Sale", b =>
                {
                    b.Navigation("SaleProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
