// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence.Database;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(DatabaseService))]
    partial class DatabaseServiceModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0-preview.5.22302.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Domain.Customers.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Martin Fowler"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Uncle Bob"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Kent Beck"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Brenda Delacruz"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Harvir Estes"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Maurice Boyd"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Claire Lacey"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Mahamed Vincent"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Clayton Whitfield"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Cali Spencer"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Evie-Mai Fountain"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Nia Hook"
                        });
                });

            modelBuilder.Entity("Domain.Employees.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Eric Evans"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Greg Young"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Udi Dahan"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Rhia Hatfield"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Tasnim Stewart"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Neve Kidd"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Ezekiel Zamora"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Donnie Everett"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Renae Mcclure"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Lucian Donald"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Mea Craft"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Neo Black"
                        });
                });

            modelBuilder.Entity("Domain.Products.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasPrecision(6, 3)
                        .HasColumnType("decimal(6,3)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Spaghetti",
                            Price = 5m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Lasagna",
                            Price = 10m
                        },
                        new
                        {
                            Id = 3,
                            Name = "Ravioli",
                            Price = 15m
                        },
                        new
                        {
                            Id = 4,
                            Name = "Salad",
                            Price = 5m
                        },
                        new
                        {
                            Id = 5,
                            Name = "Sandwich",
                            Price = 3m
                        },
                        new
                        {
                            Id = 6,
                            Name = "Tuna Steak",
                            Price = 9m
                        },
                        new
                        {
                            Id = 7,
                            Name = "Shrimp",
                            Price = 12m
                        },
                        new
                        {
                            Id = 8,
                            Name = "Rice",
                            Price = 7m
                        },
                        new
                        {
                            Id = 9,
                            Name = "Pizza",
                            Price = 12m
                        },
                        new
                        {
                            Id = 10,
                            Name = "Hamburger",
                            Price = 8m
                        });
                });

            modelBuilder.Entity("Domain.Sales.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("Sales");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerId = 1,
                            Date = new DateTime(2022, 7, 2, 0, 0, 0, 0, DateTimeKind.Local),
                            EmployeeId = 1,
                            ProductId = 1,
                            Quantity = 0,
                            TotalPrice = 0m,
                            UnitPrice = 0m
                        },
                        new
                        {
                            Id = 2,
                            CustomerId = 2,
                            Date = new DateTime(2022, 7, 3, 0, 0, 0, 0, DateTimeKind.Local),
                            EmployeeId = 2,
                            ProductId = 2,
                            Quantity = 0,
                            TotalPrice = 0m,
                            UnitPrice = 0m
                        },
                        new
                        {
                            Id = 3,
                            CustomerId = 3,
                            Date = new DateTime(2022, 7, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            EmployeeId = 3,
                            ProductId = 3,
                            Quantity = 0,
                            TotalPrice = 0m,
                            UnitPrice = 0m
                        });
                });

            modelBuilder.Entity("Domain.Sales.Sale", b =>
                {
                    b.HasOne("Domain.Customers.Customer", "Customer")
                        .WithOne("Sale")
                        .HasForeignKey("Domain.Sales.Sale", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Employees.Employee", "Employee")
                        .WithOne("Sale")
                        .HasForeignKey("Domain.Sales.Sale", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Products.Product", "Product")
                        .WithOne("Sale")
                        .HasForeignKey("Domain.Sales.Sale", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Employee");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Domain.Customers.Customer", b =>
                {
                    b.Navigation("Sale")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Employees.Employee", b =>
                {
                    b.Navigation("Sale")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Products.Product", b =>
                {
                    b.Navigation("Sale")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
